const express = require('express')
const { connectdb } = require('./src/config/db')
const { connectcloudinary } = require('./src/config/cloudinary')
const Studentrouter = require('./src/api/routes/student')
const Cursorouter = require('./src/api/routes/curso')
require('dotenv').config()
const app = express()
connectdb()
connectcloudinary()
app.use(express.json())
app.use('/api/v1/students', Studentrouter)
app.use('/api/v1/curso', Cursorouter)
app.listen(3000, () => {
  console.log('http://localhost:3000')
})
